config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'games#index'
  resources :games
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true, length: (5..300)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    def index
        @games=Game.all
    end
    
    def new
        @game = Game.new
    end
    
    def create
        @game = Game.create(game_params)
        
        if @game.valid?
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
        end
    end
    
    private
    
    def game_params
        params.require(:game).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<% @games.each do |game| %>
  <div class="booyah-box col-10 offset-1"> 
    <h1><%= game.name %></h1><br />
    <p><%= game.description %></p><br />
  </div>

  <hr />
 <% end %>

<%= link_to 'new', new_game_path %>

app/views/games/new.html.erb
<%= simple_form_for @game do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <br />
  <%= f.submit "Create" %>
<% end %>

<%= link_to 'Home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Games Database</h1>
    
    <%= yield %>
  </body>
</html>